default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("DATABASE_POOL_SIZE") { ENV.fetch("RAILS_MAX_THREADS", 5).to_i } %>
  connect_timeout: 2
  checkout_timeout: 2
  variables:
      statement_timeout: <%= ENV.fetch("STATEMENT_TIMEOUT", 2500).to_i %>

development:
  <<: *default
  url: <%= ENV.fetch("DATABASE_URL", "postgres://organicelectronics:Oe-5268452684@127.0.0.1:5432/forem_development") %>
  variables:
      statement_timeout: <%= ENV.fetch("STATEMENT_TIMEOUT", 10_000).to_i %>

test:
  <<: *default
  url: <%= ENV.fetch("TEST_DATABASE_URL", "postgres://organicelectronics:Oe-5268452684@127.0.0.1:5432/forem_test") %>
  variables:
      statement_timeout: <%= ENV.fetch("STATEMENT_TIMEOUT", 10_000).to_i %>

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
  database: <%= ENV["DATABASE_NAME"] %>